<?php

namespace AL\GsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends EntityRepository
{
}
