<?php

namespace AL\GsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends EntityRepository
{
    
    /*
     * Récupère la fiche de frais correspondant au mois ainsi que l'utilisateur fournit en paramètres
     */
    public function byUserAndDate($date,$user){
        return  $this->createQueryBuilder('u')
                     ->where('u.utilisateur = :user and u.dateRedac like :date')
                     ->setParameter('user', $user)
                     ->setParameter('date', $date.'%')
                     ->getQuery()
                     ->getOneOrNullResult();
    }
    
    /**
     * Récupère uniquement les fiches de frais du mois actuel ainsi que celles du mois précédent 
     */
    public function consulterByUserAndDate($user,$date){
        return  $this->createQueryBuilder('u')
                     ->where('u.utilisateur = :user and u.dateRedac < :date')
                     ->orderBy('u.dateRedac ',' DESC')
                     ->setParameter('user', $user)
                     ->setParameter('date', $date)
                     ->getQuery()
                     ->getResult();
    }
}
