<?php

namespace AL\GsbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends EntityRepository
{
    
    public function byUserAndDate($date,$user){
        return  $this->createQueryBuilder('u')
                     ->where('u.utilisateur = :user and u.dateRedac like :date')
                     ->setParameter('user', $user)
                     ->setParameter('date', $date.'%')
                     ->getQuery()
                     ->getOneOrNullResult();
    }
}
